# Form implementation generated from reading ui file 'MainWindow_UI.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.wgt_main = QtWidgets.QWidget(MainWindow)
        self.wgt_main.setStyleSheet("#frm_main{\n"
"background-color : #282828;\n"
"}")
        self.wgt_main.setObjectName("wgt_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wgt_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frm_main = QtWidgets.QFrame(self.wgt_main)
        self.frm_main.setStyleSheet("")
        self.frm_main.setObjectName("frm_main")
        self.lyt_main = QtWidgets.QVBoxLayout(self.frm_main)
        self.lyt_main.setContentsMargins(15, 15, 15, 15)
        self.lyt_main.setObjectName("lyt_main")
        self.frm_middle_content = QtWidgets.QFrame(self.frm_main)
        self.frm_middle_content.setStyleSheet("#frm_left_menu{\n"
"background-color:#5d5d5d;\n"
"border: 1px solid white;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#frm_right_scene{\n"
"background-color:#5d5d5d;\n"
"border: 1px solid white;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"#frm_left_menu_buttons QPushButton{\n"
" background-color: #FE6E00;\n"
" border-style: solid;\n"
" border-width:1px;\n"
" border-radius:20px;\n"
" border-color: white;\n"
"\n"
"}\n"
"\n"
"#frm_left_menu_buttons QPushButton:hover{\n"
" background-color: #FF8303;\n"
"\n"
"\n"
"}")
        self.frm_middle_content.setObjectName("frm_middle_content")
        self.lyt_middle_content = QtWidgets.QHBoxLayout(self.frm_middle_content)
        self.lyt_middle_content.setSpacing(15)
        self.lyt_middle_content.setObjectName("lyt_middle_content")
        self.frm_left_menu = QtWidgets.QFrame(self.frm_middle_content)
        self.frm_left_menu.setMinimumSize(QtCore.QSize(120, 0))
        self.frm_left_menu.setMaximumSize(QtCore.QSize(140, 16777215))
        self.frm_left_menu.setObjectName("frm_left_menu")
        self.lyt_left_menu = QtWidgets.QVBoxLayout(self.frm_left_menu)
        self.lyt_left_menu.setContentsMargins(6, 6, 6, 6)
        self.lyt_left_menu.setObjectName("lyt_left_menu")
        self.frm_left_menu_buttons = QtWidgets.QFrame(self.frm_left_menu)
        self.frm_left_menu_buttons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_left_menu_buttons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_left_menu_buttons.setObjectName("frm_left_menu_buttons")
        self.lyt_left_menu_buttons = QtWidgets.QVBoxLayout(self.frm_left_menu_buttons)
        self.lyt_left_menu_buttons.setContentsMargins(0, 0, 0, 0)
        self.lyt_left_menu_buttons.setObjectName("lyt_left_menu_buttons")
        self.pbtn_menu_loadImage = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_loadImage.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_loadImage.setStyleSheet("")
        self.pbtn_menu_loadImage.setObjectName("pbtn_menu_loadImage")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_loadImage)
        self.pbtn_menu_segment = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_segment.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_segment.setObjectName("pbtn_menu_segment")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_segment)
        self.pbtn_menu_skeletonize = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_skeletonize.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_skeletonize.setObjectName("pbtn_menu_skeletonize")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_skeletonize)
        self.pbtn_menu_analyse = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_analyse.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_analyse.setObjectName("pbtn_menu_analyse")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_analyse)
        self.pbtn_menu_report = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_report.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_report.setObjectName("pbtn_menu_report")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_report)
        self.pbtn_menu_close = QtWidgets.QPushButton(self.frm_left_menu_buttons)
        self.pbtn_menu_close.setMinimumSize(QtCore.QSize(60, 40))
        self.pbtn_menu_close.setObjectName("pbtn_menu_close")
        self.lyt_left_menu_buttons.addWidget(self.pbtn_menu_close)
        self.lyt_left_menu.addWidget(self.frm_left_menu_buttons, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.lyt_middle_content.addWidget(self.frm_left_menu)
        self.frm_right_scene = QtWidgets.QFrame(self.frm_middle_content)
        self.frm_right_scene.setObjectName("frm_right_scene")
        self.lyt_right_scene = QtWidgets.QVBoxLayout(self.frm_right_scene)
        self.lyt_right_scene.setObjectName("lyt_right_scene")
        self.frm_right_scene_content = QtWidgets.QFrame(self.frm_right_scene)
        self.frm_right_scene_content.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_right_scene_content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_right_scene_content.setObjectName("frm_right_scene_content")
        self.lyt_right_scene_content = QtWidgets.QVBoxLayout(self.frm_right_scene_content)
        self.lyt_right_scene_content.setObjectName("lyt_right_scene_content")
        self.wgts_sceneContent = QtWidgets.QStackedWidget(self.frm_right_scene_content)
        self.wgts_sceneContent.setObjectName("wgts_sceneContent")
        self.page_report = QtWidgets.QWidget()
        self.page_report.setObjectName("page_report")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_report)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_report)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.wgts_sceneContent.addWidget(self.page_report)
        self.page_image_processing = QtWidgets.QWidget()
        self.page_image_processing.setObjectName("page_image_processing")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_image_processing)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_image = QtWidgets.QFrame(self.page_image_processing)
        self.frm_image.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_image.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_image.setObjectName("frm_image")
        self.lyt_image = QtWidgets.QVBoxLayout(self.frm_image)
        self.lyt_image.setObjectName("lyt_image")
        self.verticalLayout_3.addWidget(self.frm_image)
        self.wgts_sceneContent.addWidget(self.page_image_processing)
        self.lyt_right_scene_content.addWidget(self.wgts_sceneContent)
        self.lyt_right_scene.addWidget(self.frm_right_scene_content)
        self.lyt_middle_content.addWidget(self.frm_right_scene)
        self.lyt_main.addWidget(self.frm_middle_content)
        self.verticalLayout_2.addWidget(self.frm_main)
        MainWindow.setCentralWidget(self.wgt_main)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbtn_menu_loadImage.setText(_translate("MainWindow", "Load Image"))
        self.pbtn_menu_segment.setText(_translate("MainWindow", "Segment"))
        self.pbtn_menu_skeletonize.setText(_translate("MainWindow", "Skeletonize"))
        self.pbtn_menu_analyse.setText(_translate("MainWindow", "Analyse"))
        self.pbtn_menu_report.setText(_translate("MainWindow", "Report"))
        self.pbtn_menu_close.setText(_translate("MainWindow", "Close"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
